# Spring Config
spring:
  datasource:
    url: jdbc:h2:mem:pricesdb;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Logging Config
logging:
  level:
    org:
      hibernate:
        sql: info